### ISSUE TITLE
Confusing Naming System for Bill of Material Parts

### ISSUE THREAD

**Issue by MichaelPereira36** [SpencerGood1/CerealKillerContainers#2]
In the Bill of Materials document the part numbers are confusing and do not properly define the part. The current naming convention could be easily confused with the car naming convention defined in the Glossary since "C" stands for construction and "P" stands for pickup.

**Comment by SpencerGood1** [comment]
Updated bill of materials document to reflect a strictly numerical numbering system to prevent confusion with glossary terms.
