### ISSUE TITLE
Who is Verifying the Internal Documents?

### ISSUE THREAD

**Issue by MichaelPereira36** [SpencerGood1/CerealKillerContainers#3]
After looking over the Bill of Materials, Glossary, and Master Document List, who is verifying that the information provided in these documents is correct? I did notice a signature on the Bill of Materials and the Glossary but it did not include any information as to what position that person held. Also, the Master Document List did not have a signature at all.

Would it also be possible to add another required signature for the person who added or edited the document? This way there is a two-person verification that the information provided is correct and that nothing is missing.

**Comment by SpencerGood1** [comment]
The signature at the bottom will always be either the signature of the project manager or the customer. Any edits to the bill of materials, glossary, or master document list will always be done by the project manager so don't require additional signatures. In most cases a second signature would be great for ensuring accuracy, but in this case it is the sole responsibility of the project manager to make sure these three documents are updated correctly.
